// GENERATED by scripts/gen-i18n.mjs — do not edit.
// Source of truth: src/locales/*.json. Regenerate with `npm run i18n:gen`.
// English is absent by design: it comes from the t() defaults in the code.
/* no translated locales yet */
